### PR TITLE
Added custom graph creation and undirected/directed switching

### PR DESCRIPTION
**Pull request by HKH515**

### CODE REVIEW

**Comment by rostam** [comment]
I tried to add a vertex by selecting freehand drawing. It did not work.
Can you please explain me how I can use it?

I also saw that you have added a session concept:
String sessionID = infos[4];
handleSession(sessionID);

Just for my understanding, do you want to manage users?
Can you please explain me a little bit what that is for?
And why is important?

The directed and undirected switch is working.
I will handle the pull request after your answers.

**Comment by rostam** [comment]
OK. I understand now. The freehand drawing works in Google Chrome and does not work in Firefox.

**Comment by HKH515** [comment]
Yeah we added support for concurrent users, the plan is to host this on a server, right? if so then we must be able to handle concurrent users, otherwise all users would interact with the same graph, the "freehand drawing" option in the drop-down list can be removed, we decided that the best way to draw custom graphs would be to just click on the canvas.

We are aware of the issue of the custom drawing not working on firefox, we could not find out why.

Hope this answers your questions.

**Comment by rostam** [comment]
Hi Hannes and Alex,

I have merged your pull request.
Since it is needed to resolve some conflicts,
the structure of your code maybe has been changed a little bit.
I also corrected the problem with firefox:
To understand what the errors was,
look at the changes in the function "addSingleVertex" under 
https://github.com/rostam/GTea/blob/master/src/main/resources/web/dashboard/js/cytoscape_related_functions.js#L84
Just feel free to write me if you did not understand some changes.

I added the following javascript function which contains most of your
functions:
https://github.com/rostam/GTea/blob/master/src/main/resources/web/dashboard/js/cytoscape_related_functions.js

I changed the name of the index2.html file to index.html.

Also instead of the button "Select Type" that you were defined,
I just got the action of "onchange" of "select".
So, the user can change the type of graph by just selecting
directed and undirected (so no button).

You will see some new features that I have been added since last time
which do not have any major influence on your works. For example, I added the button "Load Only" beside "Load and Draw". This is for big graphs where the user only wants to compute some reports and does not want to visualized the graph.

Thanks for great work.

**Pull request merged**
